banned-substrings:
  - fuck
  - shit
  - bitch
  - cunt
  - dick
  - pussy
  - nigger
  - slut
  - whore
  - bastard
  - piss
  - crap
  - cock
  - blowjob
  - wanker
  - jerk
  - twat
  - motherfucker
  - sonofabitch
  - asshat
  - asshole
  - ballbag
  - dickhead
  - knobhead
  - tosser
  - cuntface
  - dickwad
  - dipshit
  - fellatio
  - fucker
  - gangbang
  - handjob
  - jackoff
  - jizz
  - muff
  - niggers
  - nignog
  - nutter
  - pecker
  - prick
  - queer
  - rimjob
  - scrotum
  - skeet
  - slutbag
  - titfuck
  - titties
  - tranny
  - vibrator
  - wetback
  - whorebag